---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---
### Pre-processing ATAC-seq data and fit CENTIPEDE model

* [Pre-processing ATAC-seq data](ATACseq_preprocessing_pipeline.html)

* [fit CENTIPEDE model](fit_centipede_ATACseq.html)

### Compare TF binding between normoxia and hypoxia using CENTIPEDE predictions on ATAC-seq data

* [Compare CENTIPEDE predictions for HIF1A](compare_centipede_predictions_HIF1A.html)

* [Compare CENTIPEDE predictions for CTCF](compare_centipede_predictions_CTCF.html)

* [Compare CENTIPEDE predictions for MEF2D](compare_centipede_predictions_MEF2D.html)

### Compare TF binding using CENTIPEDE predictions for motif matches in differential accessbile regions between normoxia and hypoxia

* [Compare CENTIPEDE predictions for HIF1A](compare_centipede_predictions_DiffACregions_HIF1A.html)

* [Compare CENTIPEDE predictions for CTCF](compare_centipede_predictions_DiffACregions_CTCF.html)

* [Compare CENTIPEDE predictions for MEF2D](compare_centipede_predictions_DiffACregions_MEF2D.html)

